source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "rails", "~> 7.0.4.1"

gem "activerecord-session_store"
gem "acts_as_tenant"
gem "aws-sdk-s3", "~> 1"
gem "browser"
gem "bugsnag"
gem "cloudinary", "1.15.0"
gem "cocoon"
gem "coffee-rails"
gem "db_text_search"
gem "detectify", github: "rubygarage/detectify"
gem "devise"
gem "faraday"
gem "friendly_id"
gem "exception_handler"
gem "firebase"
gem "jbuilder"
gem "jquery-rails"
gem "jwt"
gem "kaminari"
gem "mimemagic"
gem "mysql2"
gem "paperclip"
gem "parsley-rails"
gem "postmark"
gem "postmark-rails"
gem "puma"
gem "pusher"
gem "redis-rails"
gem "sass-rails"
gem "semantic-ui-sass"
gem "sidekiq"
gem "sidekiq-cron"
gem "simple_calendar"
gem "stripe"
gem "summernote-rails"
gem "therubyracer"
gem "turbolinks"
gem "twilio-ruby"
gem "uglifier"

group :development, :test do
  gem "better_errors"
  gem "binding_of_caller"
  gem "dotenv-rails"
  gem "pry-rails"
  gem "rspec-rails"
  gem "thin"
end

gem "meritadmin", path: "meritadmin"
