---
development:
  cloud_name: <%= ENV['CLOUDINARY_API_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_file_support: false
  secure: true
  upload_preset: <%= ENV['CLOUDINARY_API_UNSIGNED_UPLOAD_PRESET'] %>
production:
  cloud_name: <%= ENV['CLOUDINARY_API_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_file_support: true
  secure: true
  upload_preset: <%= ENV['CLOUDINARY_API_UNSIGNED_UPLOAD_PRESET'] %>
test:
  cloud_name: <%= ENV['CLOUDINARY_API_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_file_support: false
  secure: false
  upload_preset: <%= ENV['CLOUDINARY_API_UNSIGNED_UPLOAD_PRESET'] %>
